// <auto-generated />
namespace BusTicketBookingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatelistreservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatelistreservation));
        
        string IMigrationMetadata.Id
        {
            get { return "201707190224045_update-list-reservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
