DROP TABLE IF EXISTS Passenger
CREATE TABLE Passenger 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    UserID NVARCHAR(50) NOT NULL UNIQUE,
	FirstName NVARCHAR(25) NOT NULL,
	LastName NVARCHAR(25) NOT NULL,
	PhoneNumber VARCHAR(15) NOT NULL,
	BankName NVARCHAR(25) NOT NULL,
	BankAccountNumber VARCHAR(25) NOT NULL
)

DROP TABLE IF EXISTS Place
CREATE TABLE Place 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL
)

DROP TABLE IF EXISTS Route
CREATE TABLE Route 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Origin NVARCHAR(50) NOT NULL,
	Destination NVARCHAR(50) NOT NULL
)

DROP TABLE IF EXISTS BusVehicle
CREATE TABLE BusVehicle 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(25) NOT NULL,
	RouteID INT NOT NULL,
	Class VARCHAR(25) NOT NULL,
	Capacity INT,
	Fare INT, 
	DepartureTime datetime
)
ALTER TABLE BusVehicle
ADD CONSTRAINT FK_BusRoute FOREIGN KEY (RouteID)
REFERENCES Route(Id) ON DELETE CASCADE

DROP TABLE IF EXISTS Reservation
CREATE TABLE Reservation 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	TotalSeat INT NOT NULL,
	SeatNumber VARCHAR(100),
	PurchasedOn DATETIME NOT NULL, 
	PassengerID int NOT NULL, 
	BusID int NOT NULL, 
	TotalAmount INT NOT NULL,
	IsConfirmed BIT NOT NULL
)
ALTER TABLE Reservation
ADD CONSTRAINT FK_TicketPassenger FOREIGN KEY (PassengerID)
REFERENCES Passenger(Id) ON DELETE CASCADE
ALTER TABLE Reservation
ADD CONSTRAINT FK_TicketBus FOREIGN KEY (BusID)
REFERENCES BusVehicle(Id) ON DELETE CASCADE